# Avatar Framer Config
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: SoCIT General Assembly 2022 | FasticFrame
description: >- # this means to ignore newlines"
  A simple tool to create framed profile pictures for social media in support of a cause.
  Dynamically generate a static site based off of the number of frame images provided.

repository-link: "https://github.com/jpcsapc/fasticframe"

# Copy
# Fill in your copy for the title and steps here
# 
title-text: "SoCIT Fest 2022"
step-1: "Upload your picture or another square image below."
step-2: "Use the photo tools to scale, rotate, and move your image over the preview."
step-3: "Download your new profile picture:"
step-4: "Post on social media with the following as your caption!"

footer-text: "&copy; 2022 Junior Philippine Computer Society - Asia Pacific College. All rights reserved."

# Buttons and upload form
#
upload-text: "Drop files here or click to upload."
download-button-text: "Download your new profile picture"

# Logo & Favicon
# 
logo: "socit-orgs.png"
favicon: "favicon.ico"

# Open Graph and Twitter Cards
#
og-title: SoCIT Fest 2022
og-description: SoCIT Fest 2022
og-url: https://jpcsapc.github.io/socitga22-frame
og-image: "og-image.png"
og-image-width: 1280
og-image-height: 640
twitter-card: summary_large_image
twitter-description: "Create your framed profile picture for the SoCIT General Assembly 2022!"
twitter-image: "og-image.png"
twitter-handle: "@jpcs_apc"

caption-lines:
  - "𝚄0𝟿𝙳𝚂𝚅𝚀 𝚁0𝚅𝙾𝚁𝚅𝙹𝙱𝚃𝙰 𝚀𝚅𝙽𝚃𝚁𝚄𝟷𝙲𝚃𝙵𝚔"
  - "👩‍💻👨‍💻 SOCIT GENERAL ASSEMBLY 2022 💾"
  - >-
    🤔 Were you able to guess the mystery word?<br>
    💻 It was encoded using Base64, a “binary-to-text encoding scheme”!<br>
    😏 If not, better luck next time!
  - "In collaboration with the SoCIT Organizations of Asia Pacific College, we are inviting everyone to join this event this coming August 22, 2022, from 1:00 PM – 4:30 PM. We would love you to come and meet with our fellow members, which will surely make you feel at home and a part of our organizations."
  - "We’ll tackle many topics related to Information Technology (IT), the industry, and the benefits that you’ll gain if you choose to be a member of one of the SoCIT organizations. You’ve got a lot to choose from: Junior Philippine Computer Society (JPCS-APC), Junior Information Systems Security Association (JISSA), Microsoft Community (APC-MSC), and Gaming Genesis."
  - "The assembly will be held inside the school, at the APC Multipurpose Hall 1 (MPH1), and on Microsoft Teams, for those who’d prefer to join us online."
  - "📌 Register now and learn more about everything that we have in store for you!"
  - "https://tinyurl.com/SoCITGA22-RegForm"
  - "🔗 Join the fun and apply our frame now:"
  - "https://tinyurl.com/SoCITGA22-Frame"
  - "#BeARam<br>#SoCITGeneralAssembly"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
# 
exclude:
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - "*.config.js"
  - "*.config.json"
  - "package*.json"
